=== criusx/dramsimii/DRAMSimII/memoryDefinitions/dramspec.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT IDD0 (#PCDATA)>
<!ELEMENT IDD2N (#PCDATA)>
<!ELEMENT IDD2P (#PCDATA)>
<!ELEMENT IDD3N (#PCDATA)>
<!ELEMENT IDD3P (#PCDATA)>
<!ELEMENT IDD4R (#PCDATA)>
<!ELEMENT IDD4W (#PCDATA)>
<!ELEMENT IDD5A (#PCDATA)>
<!ELEMENT autoPrecharge (#PCDATA)>
<!ELEMENT autoRefreshPolicy (#PCDATA)>
<!ELEMENT banks (#PCDATA)>
<!ELEMENT cacheLineSize (#PCDATA)>
<!ELEMENT channelWidth (#PCDATA)>
<!ELEMENT channels (#PCDATA)>
<!ELEMENT clockGranularity (#PCDATA)>
<!ELEMENT columnSize (#PCDATA)>
<!ELEMENT columns (#PCDATA)>
<!ELEMENT commandOrderingAlgorithm (#PCDATA)>
<!ELEMENT completionQueueDepth (#PCDATA)>
<!ELEMENT cpuToMemoryClockRatio (#PCDATA) >
<!ELEMENT datarate (#PCDATA)>
<!ELEMENT DQperDRAM (#PCDATA)>
<!ELEMENT DQSperDRAM (#PCDATA)>
<!ELEMENT DMperDRAM (#PCDATA)>
<!ELEMENT dramspec (timing, power, simulationParameters)>
<!ATTLIST dramspec
	type CDATA #REQUIRED
	xmlns:xsi CDATA #IMPLIED
	xsi:noNamespaceSchemaLocation CDATA #IMPLIED
>
<!ELEMENT eventQueueDepth (#PCDATA)>
<!ELEMENT historyQueueDepth (#PCDATA)>
<!ELEMENT inputFile (#PCDATA)>
<!ATTLIST inputFile type CDATA #REQUIRED>
<!ELEMENT maxVCC (#PCDATA)>
<!ELEMENT frequencySpec (#PCDATA)>
<!ELEMENT outFile (#PCDATA)>
<!ATTLIST outFile type CDATA #REQUIRED>
<!ELEMENT perBankQueueDepth (#PCDATA)>
<!ELEMENT PdqRD (#PCDATA)>
<!ELEMENT PdqWR (#PCDATA)>
<!ELEMENT PdqRDoth (#PCDATA)>
<!ELEMENT PdqWRoth (#PCDATA)>
<!ELEMENT physicalAddressMappingPolicy (#PCDATA)>
<!ELEMENT postedCAS (#PCDATA)>
<!ELEMENT power (PdqRD, PdqWR, PdqRDoth, PdqWRoth, DQperDRAM, DQSperDRAM, DMperDRAM, frequencySpec, maxVCC, systemVDD, IDD0, IDD2P, IDD2N, IDD3P, IDD3N, IDD4R, IDD4W, IDD5A)>
<!ELEMENT ranks (#PCDATA)>
<!ELEMENT readPercentage (#PCDATA)>
<!ELEMENT readWriteGrouping (#PCDATA)>
<!ELEMENT refreshQueueDepth (#PCDATA)>
<!ELEMENT refreshTime (#PCDATA)>
<!ELEMENT requestCount (#PCDATA)>
<!ELEMENT rowBufferPolicy (#PCDATA)>
<!ELEMENT rowSize (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT seniorityAgeLimit (#PCDATA)>
<!ELEMENT shortBurstRatio (#PCDATA)>
<!ELEMENT simulationParameters (shortBurstRatio, readPercentage, outFile, requestCount, inputFile, cpuToMemoryClockRatio)>
<!ELEMENT systemConfigurationType (#PCDATA)>
<!ELEMENT systemVDD (#PCDATA)>
<!ELEMENT tAL (#PCDATA)>
<!ELEMENT tBufferDelay (#PCDATA)>
<!ELEMENT tBurst (#PCDATA)>
<!ELEMENT tCAS (#PCDATA)>
<!ELEMENT tCMD (#PCDATA)>
<!ELEMENT tCWD (#PCDATA)>
<!ELEMENT tFAW (#PCDATA)>
<!ELEMENT tRAS (#PCDATA)>
<!ELEMENT tRC (#PCDATA)>
<!ELEMENT tRCD (#PCDATA)>
<!ELEMENT tREFI (#PCDATA)>
<!ELEMENT tRFC (#PCDATA)>
<!ELEMENT tRP (#PCDATA)>
<!ELEMENT tRRD (#PCDATA)>
<!ELEMENT tRTP (#PCDATA)>
<!ELEMENT tRTRS (#PCDATA)>
<!ELEMENT tWR (#PCDATA)>
<!ELEMENT tWTR (#PCDATA)>
<!ELEMENT timing (datarate, clockGranularity, channels, channelWidth, physicalAddressMappingPolicy, rowBufferPolicy, ranks, banks, rows, rowSize, columns, columnSize, tBufferDelay, tBurst, tCAS, tCMD, tCWD, tFAW, tRAS, tRC, tRCD, tRFC, tRRD, tRP, tRTP, tRTRS, tWR, tWTR, postedCAS, tAL, autoRefreshPolicy, refreshTime, tREFI, commandOrderingAlgorithm, transactionOrderingAlgorithm, perBankQueueDepth, systemConfigurationType, cacheLineSize, historyQueueDepth, completionQueueDepth, transactionQueueDepth, eventQueueDepth, refreshQueueDepth, seniorityAgeLimit, readWriteGrouping, autoPrecharge)>
<!ELEMENT transactionOrderingAlgorithm (#PCDATA)>
<!ELEMENT transactionQueueDepth (#PCDATA)>

=== criusx/dramsimii/DRAMSimII/memoryDefinitions/DDR2-800-4-4-4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="style2.xsl"?>
<!DOCTYPE dramspec SYSTEM "dramspec.dtd">
<dramspec type="ddr2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema2.xsd">
	<timing>
		<datarate>800000000</datarate>
		<clockGranularity>2</clockGranularity>
		<channels>1</channels>
		<channelWidth>8</channelWidth>
		<!--burgerBase, closePageBaseline, intel845g, sdramBase, sdramClosePage, sdramHiperf-->
		<physicalAddressMappingPolicy>closePageBaseline</physicalAddressMappingPolicy>
		<rowBufferPolicy>closePage</rowBufferPolicy>
		<ranks>4</ranks>
		<banks>8</banks>
		<rows>16384</rows>
		<rowSize>16</rowSize>
		<!-- columns * columnSize = pageSize -->
		<columns>1024</columns>
		<columnSize>16</columnSize>
		<tBufferDelay>6</tBufferDelay>
		<tBurst>8</tBurst>
		<tCAS>5</tCAS>
		<tCMD>2</tCMD>
		<tCWD>8</tCWD>
		<tFAW>28</tFAW>
		<!--time between a row access and data restoration in the data array-->
		<tRAS>36</tRAS>
		<!--minimum activate-to-activate timing (same bank), tRC = tRAS + tRP-->
		<tRC>46</tRC>
		<tRCD>10</tRCD>
		<!--minimum refresh-to-refresh cycle time-->
		<tRFC>102</tRFC>
		<!--minimum activate-to-activate timing (different bank)-->
		<tRRD>6</tRRD>
		<tRP>10</tRP>
		<tRTP>6</tRTP>
		<tRTRS>2</tRTRS>
		<tWR>12</tWR>
		<tWTR>6</tWTR>
		<postedCAS>true</postedCAS>
		<!--additive latency, the dram device may buffer a command for up to this length of time to allow it to be transferred and help until timing parameters are met, see Micron doc TN4710-->
		<tAL>10</tAL>
		<!--may be none, refreshOneChanAllRankAllBank, etc.-->
		<autoRefreshPolicy>none</autoRefreshPolicy>
		<!--given in us-->
		<refreshTime>64000</refreshTime>
		<!--average periodic refresh time-->
		<tREFI>6240</tREFI>
		<commandOrderingAlgorithm>strict</commandOrderingAlgorithm>
		<!--may be 'strict' or 'RIFF'-->
		<transactionOrderingAlgorithm>strict</transactionOrderingAlgorithm>
		<perBankQueueDepth>8</perBankQueueDepth>
		<!--sets FBD mode otherwise-->
		<systemConfigurationType>baseline</systemConfigurationType>
		<cacheLineSize>64</cacheLineSize>
		<historyQueueDepth>16</historyQueueDepth>
		<completionQueueDepth>32</completionQueueDepth>
		<transactionQueueDepth>8</transactionQueueDepth>
		<eventQueueDepth>8</eventQueueDepth>
		<refreshQueueDepth>8</refreshQueueDepth>
		<seniorityAgeLimit>256</seniorityAgeLimit>
		<readWriteGrouping>false</readWriteGrouping>
		<!--able to issue CAS+Pre commands, effective with close page-->
		<autoPrecharge>true</autoPrecharge>
	</timing>
	<power>
		<!--all in terms of mW-->
		<PdqRD>1.1</PdqRD>
		<PdqWR>8.2</PdqWR>
		<PdqRDoth>0</PdqRDoth>
		<PdqWRoth>0</PdqWRoth>
		<!--pins on the dram devices-->
		<DQperDRAM>16</DQperDRAM>
		<DQSperDRAM>4</DQSperDRAM>
		<DMperDRAM>2</DMperDRAM>
		<frequencySpec>600000000</frequencySpec>
		<maxVCC>1.9</maxVCC>
		<systemVDD>1.8</systemVDD>
		<!--all are in mA-->
		<!--maximum active precharge current-->
		<IDD0>150</IDD0>
		<!--maximum precharge power-down standby current-->
		<IDD2P>7</IDD2P>
		<!--maximum precharge standby current-->
		<IDD2N>80</IDD2N>
		<!--maximum active power-down standby current-->
		<IDD3P>10</IDD3P>
		<!--maximum active standby current-->
		<IDD3N>85</IDD3N>
		<!--maximum read burst current-->
		<IDD4R>320</IDD4R>
		<!--maximum write burst current-->
		<IDD4W>315</IDD4W>
		<!--maximum burst refresh current-->
		<IDD5A>280</IDD5A>
	</power>
	<simulationParameters>
		<shortBurstRatio>.50</shortBurstRatio>
		<readPercentage>.5</readPercentage>
		<!-- type may be gz, bz, cout, uncompressed, none -->
		<outFile type="gz">standardOutFile.gz</outFile>
		<requestCount>990000000</requestCount>
		<!--may be "mase","k6","mapped","random"-->
		<inputFile type="mase" />
	</simulationParameters>
</dramspec>
