=== criusx/dramsimii/memoryDefinitions/dramspec.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT IDD0 (#PCDATA)>
<!ELEMENT IDD1 (#PCDATA)>
<!ELEMENT IDD2N (#PCDATA)>
<!ELEMENT IDD2P (#PCDATA)>
<!ELEMENT IDD3N (#PCDATA)>
<!ELEMENT IDD3P (#PCDATA)>
<!ELEMENT IDD4R (#PCDATA)>
<!ELEMENT IDD4W (#PCDATA)>
<!ELEMENT IDD5A (#PCDATA)>
<!ELEMENT autoPrecharge (#PCDATA)>
<!ELEMENT autoRefreshPolicy (#PCDATA)>
<!ELEMENT associativity (#PCDATA)>
<!ELEMENT averageInterarrivalCycleCount (#PCDATA)>
<!ELEMENT banks (#PCDATA)>
<!ELEMENT blockSize (#PCDATA)>
<!ELEMENT cache (usingCache, associativity, cacheSize, blockSize, hitLatency, replacementPolicy, nmruTrackingCount) >
<!ELEMENT cacheLineSize (#PCDATA)>
<!ELEMENT channelWidth (#PCDATA)>
<!ELEMENT channels (#PCDATA)>
<!ELEMENT clockGranularity (#PCDATA)>
<!ELEMENT columnSize (#PCDATA)>
<!ELEMENT columns (#PCDATA)>
<!ELEMENT commandOrderingAlgorithm (#PCDATA)>
<!ELEMENT cpuToMemoryClockRatio (#PCDATA) >
<!ELEMENT datarate (#PCDATA)>
<!ELEMENT decodeWindow (#PCDATA)>
<!ELEMENT dimms (#PCDATA)>
<!ELEMENT DQperDRAM (#PCDATA)>
<!ELEMENT DQSperDRAM (#PCDATA)>
<!ELEMENT DMperDRAM (#PCDATA)>
<!ELEMENT dramspec (setup, timing, power, simulationParameters)>
<!ATTLIST dramspec
type CDATA #REQUIRED
xmlns:xsi CDATA #IMPLIED
xsi:noNamespaceSchemaLocation CDATA #IMPLIED
>
<!ELEMENT epoch (#PCDATA)>
<!ELEMENT hitLatency (#PCDATA)>
<!ELEMENT inputFile (#PCDATA)>
<!ATTLIST inputFile type CDATA #REQUIRED>
<!ELEMENT maxVCC (#PCDATA)>
<!ELEMENT cacheSize (#PCDATA)>
<!ELEMENT frequencySpec (#PCDATA)>
<!ELEMENT nmruTrackingCount (#PCDATA)>
<!ELEMENT outFile (#PCDATA)>
<!ELEMENT outFileDirectory (#PCDATA)>
<!ATTLIST outFile type (gz|bz|cout|uncompressed|none) #REQUIRED>
<!ELEMENT perBankQueueDepth (#PCDATA)>
<!ELEMENT PdqRD (#PCDATA)>
<!ELEMENT PdqWR (#PCDATA)>
<!ELEMENT PdqRDoth (#PCDATA)>
<!ELEMENT PdqWRoth (#PCDATA)>
<!ELEMENT physicalAddressMappingPolicy (#PCDATA)>
<!ELEMENT postedCAS (#PCDATA)>
<!ELEMENT power (PdqRD, PdqWR, PdqRDoth, PdqWRoth, DQperDRAM, DQSperDRAM, DMperDRAM,
frequencySpec, maxVCC, systemVDD, IDD0,IDD1, IDD2P, IDD2N, IDD3P, IDD3N, IDD4R, IDD4W, IDD5A)>
<!ELEMENT ranks (#PCDATA)>
<!ELEMENT readPercentage (#PCDATA)>
<!ELEMENT readWriteGrouping (#PCDATA)>
<!ELEMENT replacementPolicy (#PCDATA)>
<!ELEMENT requestCount (#PCDATA)>
<!ELEMENT rowBufferPolicy (#PCDATA)>
<!ELEMENT rowSize (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT seniorityAgeLimit (#PCDATA)>
<!ELEMENT shortBurstRatio (#PCDATA)>
<!ELEMENT simulationParameters (shortBurstRatio, readPercentage,
averageInterarrivalCycleCount, outFile, outFileDirectory, requestCount, inputFile,
cpuToMemoryClockRatio, epoch)>
<!ELEMENT systemVDD (#PCDATA)>
<!ELEMENT tAL (#PCDATA)>
<!ELEMENT tBufferDelay (#PCDATA)>
<!ELEMENT tBurst (#PCDATA)>
<!ELEMENT tCAS (#PCDATA)>
<!ELEMENT tCMD (#PCDATA)>
<!ELEMENT tCWD (#PCDATA)>
<!ELEMENT tFAW (#PCDATA)>
<!ELEMENT tRAS (#PCDATA)>
<!ELEMENT tRC (#PCDATA)>
<!ELEMENT tRCD (#PCDATA)>
<!ELEMENT tREFI (#PCDATA)>
<!ELEMENT tRFC (#PCDATA)>
<!ELEMENT tRP (#PCDATA)>
<!ELEMENT tRRD (#PCDATA)>
<!ELEMENT tRTP (#PCDATA)>
<!ELEMENT tRTRS (#PCDATA)>
<!ELEMENT tWR (#PCDATA)>
<!ELEMENT tWTR (#PCDATA)>
<!ELEMENT timing (tBufferDelay, tBurst, tCAS, tCMD, tCWD, tFAW, tRAS, tRC, tRCD, tRFC, tRRD,
tRP, tRTP, tRTRS, tWR, tWTR, tAL, tREFI, seniorityAgeLimit)>
<!ELEMENT setup (datarate, clockGranularity, channels, dimms, ranks, banks, rows, columns,
channelWidth, physicalAddressMappingPolicy, rowBufferPolicy, rowSize, columnSize,
postedCAS,autoRefreshPolicy,commandOrderingAlgorithm,
transactionOrderingAlgorithm, perBankQueueDepth, cacheLineSize, transactionQueueDepth,
decodeWindow, readWriteGrouping, autoPrecharge, cache)>
<!ELEMENT transactionOrderingAlgorithm (#PCDATA)>
<!ELEMENT transactionQueueDepth (#PCDATA)>
<!ELEMENT usingCache (#PCDATA)>
<!ATTLIST usingCache fixedLatency (true|false) #REQUIRED>

=== criusx/dramsimii/memoryDefinitions/DDR2-800-4-4-4-25E.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="style2.xsl"?>
<!DOCTYPE dramspec SYSTEM "dramspec.dtd">
<dramspec type="ddr2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema2.xsd">
	<timing>
		<!-- the number of beats per, so if a timing parameter is one cycle long, count it as two beats for DDR -->
		<datarate>800000000</datarate>
		<!-- set to 2 for DDR, DDR2, DDR3, etc. -->
		<clockGranularity>2</clockGranularity>
		<channels>2</channels>
		<channelWidth>8</channelWidth>
		<!--burgerBase, closePageBaseline, intel845g, sdramBase, sdramClosePage, sdramHiperf, closePageLowLocality, closePageHighLocality -->
		<physicalAddressMappingPolicy>closePageBaseline</physicalAddressMappingPolicy>
		<!-- openPage, closePage, closePageAggressive -->
		<rowBufferPolicy>closePageAggressive</rowBufferPolicy>
		<ranks>4</ranks>
		<banks>8</banks>
		<!-- bits per row-->
		<rows>16384</rows>
		<rowSize>16</rowSize>
		<!-- columns * columnSize = pageSize -->
		<columns>2048</columns>
		<columnSize>16</columnSize>
		<tBufferDelay>1</tBufferDelay>
		<tBurst>8</tBurst>
		<tCAS>5</tCAS>
		<tCMD>2</tCMD>
		<!--  should be equal to tCAS - 2 beats -->
		<tCWD>3</tCWD>
		<tFAW>28</tFAW>
		<!--time between a row access and data restoration in the data array-->
		<tRAS>32</tRAS>
		<!--minimum activate-to-activate timing (same bank), tRC = tRAS + tRP-->
		<tRC>46</tRC>
		<tRCD>10</tRCD>
		<!--minimum refresh-to-refresh cycle time-->
		<tRFC>84</tRFC>
		<!--minimum activate-to-activate timing (different bank)-->
		<tRRD>6</tRRD>
		<tRP>10</tRP>
		<tRTP>6</tRTP>
		<tRTRS>2</tRTRS>
		<tWR>12</tWR>
		<tWTR>6</tWTR>
		<postedCAS>true</postedCAS>
		<!--additive latency, the dram device may buffer a command for up to this length of time to allow it to be transferred and help until timing parameters are met, see Micron doc TN4710-->
		<tAL>8</tAL>
		<!--may be none, refreshOneChanAllRankAllBank, etc.-->
		<autoRefreshPolicy>refreshOneChanAllRankAllBank</autoRefreshPolicy>
		<!--given in us-->
		<refreshTime>64000</refreshTime>
		<!--average periodic refresh time, look at Micron app note TN-46-09 -->
		<tREFI>6240</tREFI>
		<!--strict, bankRoundRobin, rankRoundRobin, wangHop, greedy-->
		<commandOrderingAlgorithm>greedy</commandOrderingAlgorithm>
		<!--may be strict, RIFF-->
		<transactionOrderingAlgorithm>RIFF</transactionOrderingAlgorithm>
		<perBankQueueDepth>8</perBankQueueDepth>
		<!--sets FBD mode otherwise-->
		<systemConfigurationType>baseline</systemConfigurationType>
		<cacheLineSize>64</cacheLineSize>
		<historyQueueDepth>16</historyQueueDepth>
		<completionQueueDepth>32</completionQueueDepth>
		<transactionQueueDepth>16</transactionQueueDepth>
		<eventQueueDepth>8</eventQueueDepth>
		<refreshQueueDepth>8</refreshQueueDepth>
		<!-- used to determine how long a refresh transaction may be deprioritized relative to normal transactions -->
		<seniorityAgeLimit>512</seniorityAgeLimit>
		<!--attempts to group reads and writes together in time-->
		<readWriteGrouping>false</readWriteGrouping>
		<!--able to issue CAS+Pre commands, effective with close page, unavailable in open page RBMP -->
		<autoPrecharge>true</autoPrecharge>
	</timing>
	<power>
		<!--all in terms of mW-->
		<PdqRD>1.1</PdqRD>
		<PdqWR>8.2</PdqWR>
		<PdqRDoth>0</PdqRDoth>
		<PdqWRoth>0</PdqWRoth>
		<!--pins on the dram devices-->
		<DQperDRAM>8</DQperDRAM>
		<DQSperDRAM>4</DQSperDRAM>
		<DMperDRAM>2</DMperDRAM>
		<frequencySpec>800000000</frequencySpec>
		<maxVCC>1.9</maxVCC>
		<systemVDD>1.8</systemVDD>
		<!--all are in mA-->
		<!--maximum active precharge current-->
		<IDD0>90</IDD0>
		<!--maximum precharge power-down standby current-->
		<IDD2P>7</IDD2P>
		<!--maximum precharge standby current-->
		<IDD2N>60</IDD2N>
		<!--maximum active power-down standby current-->
		<IDD3P>50</IDD3P>
		<!--maximum active standby current-->
		<IDD3N>60</IDD3N>
		<!--maximum read burst current-->
		<IDD4R>145</IDD4R>
		<!--maximum write burst current-->
		<IDD4W>145</IDD4W>
		<!--maximum burst refresh current-->
		<IDD5A>235</IDD5A>
	</power>
	<simulationParameters>
		<shortBurstRatio>.50</shortBurstRatio>
		<readPercentage>.75</readPercentage>
		<averageInterarrivalCycleCount>4</averageInterarrivalCycleCount>
		<!-- type may be gz, bz, cout, uncompressed, none -->
		<outFile type="gz" dbreporting="false">standardOutFile.gz</outFile>
		<!-- the directory that the output files will be written to -->
		<outFileDirectory>.</outFileDirectory>
		<requestCount>75000000</requestCount>
		<!-- type may be "mase","k6","mapped","random," if random, then the value is the distrubution model, which may be 'uniform', 'gaussian' , 'poisson', 'normal' -->
		<inputFile type="random">gaussian</inputFile>
		<!--inputFile type="mase">equake.trc</inputFile-->
		<!-- used in scaling CPU ticks to memory system ticks -->
		<cpuToMemoryClockRatio>4.00</cpuToMemoryClockRatio>
		<epoch>1000000</epoch>
	</simulationParameters>
</dramspec>
